{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  labels:
    {{- include "dnavio-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size }}
{{- end }}
