apiVersion: v2
name: dnavio-platform
description: D-NAVIO Digital Twin platform — Kafka, Keycloak, MinIO
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - digital-twin
  - kafka
  - keycloak
  - minio
maintainers:
  - name: D-NAVIO Team
