apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    {{- include "dnavio-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dnavio-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak
  template:
    metadata:
      labels:
        {{- include "dnavio-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      restartPolicy: Always
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          args:
            - start-dev
            - --http-enabled=true
            - --hostname-strict=false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: admin-username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: admin-password
