apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  labels:
    {{- include "dnavio-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.storage.size }}
