apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  labels:
    {{- include "dnavio-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  admin-username: {{ .Values.keycloak.adminUsername | quote }}
  admin-password: {{ .Values.keycloak.adminPassword | quote }}
