apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    {{- include "dnavio-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "dnavio-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
